import { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import { useAuth } from '../contexts/AuthContext'
import { getChaptersWithTasks, createChapter, toggleTask, calcSubjectPercent, calcTaskTypePoints } from '../lib/data'
import { Chapter, Task, TaskType } from '../types'
import { supabase } from '../supabaseClient'
import AppShell, { Icon } from '../components/AppShell'
import ProgressRing from '../components/ProgressRing'
type ChapterWithTasks = Chapter & { tasks: Task[] }
export default function Subject() { const { subjectId } = useParams(); const { profile, user } = useAuth(); const [subjectName,setSubjectName]=useState(''); const [chapters,setChapters]=useState<ChapterWithTasks[]>([]); const [loading,setLoading]=useState(true); const [newChapterName,setNewChapterName]=useState(''); const isStudent=profile?.role==='student'
  async function load(){if(!subjectId)return;const {data}=await supabase.from('subjects').select('name').eq('id',subjectId).single();if(data)setSubjectName(data.name);setChapters(await getChaptersWithTasks(subjectId));setLoading(false)} useEffect(()=>{load()},[subjectId])
  async function add(e:React.FormEvent){e.preventDefault();if(!subjectId||!newChapterName.trim())return;await createChapter(subjectId,newChapterName.trim(),chapters.length);setNewChapterName('');load()} async function toggle(t:Task){if(!isStudent||!user)return;await toggleTask(t.id,!t.done,user.id);load()}
  const overall=calcSubjectPercent(chapters), lecture=calcTaskTypePoints(chapters,'lecture'),hw=calcTaskTypePoints(chapters,'hw'),dpp=calcTaskTypePoints(chapters,'dpp'); const stats={lecture:lecture.max?lecture.earned/lecture.max*100:0,hw:hw.max?hw.earned/hw.max*100:0,dpp:dpp.max?dpp.earned/dpp.max*100:0}
  return <AppShell title={loading ? 'Your subject' : subjectName} eyebrow="Learning map" variant="subject" action={<span className="pill"><Icon name="spark" size={13} /> Intentional progress</span>}><div className="subject-layout"><aside className="surface panel subject-hero"><ProgressRing value={overall} label="complete"/><h2>{Math.round(overall)}% mapped</h2><p className="muted tiny">Every small check-in brings the bigger picture into focus.</p></aside><section className="surface panel"><div className="subject-top"><div><h2 className="surface-title">Chapters</h2><p className="muted tiny">Mark each learning touchpoint as you finish it.</p></div><span className="pill">{chapters.length} chapters</span></div>{isStudent&&<form className="form-row" onSubmit={add}><input className="field" placeholder="Add a chapter" value={newChapterName} onChange={e=>setNewChapterName(e.target.value)}/><button className="btn btn-primary" type="submit"><Icon name="plus" size={15}/> Add</button></form>}<div className="chapter-list" style={{marginTop:18}}>{chapters.map(ch=><article className="surface chapter-card" key={ch.id}><h3>{ch.name}</h3><div className="task-toggles">{(['lecture','hw','dpp'] as TaskType[]).map(type=>{const t=ch.tasks.find(x=>x.type===type);return t?<button key={type} disabled={!isStudent} onClick={()=>toggle(t)} className={`task-toggle ${t.done?'done':''}`}>{type==='lecture'?'Lecture':type.toUpperCase()}</button>:null})}</div></article>)}{!loading&&!chapters.length&&<p className="empty">Start by adding the first chapter.</p>}</div></section></div><section className="surface panel" style={{marginTop:22}}><h2 className="surface-title">Completion signals</h2><div className="subject-grid">{Object.entries(stats).map(([name,value])=><div className="surface panel" key={name}><span className="eyebrow">{name}</span><strong>{Math.round(value)}%</strong><div className="stat-bar" style={{marginTop:10}}><i style={{width:`${value}%`}}/></div></div>)}</div></section></AppShell>
}
